### ISSUE TITLE
Differences between reference data paths

### ISSUE THREAD

**Issue by tommyli** [broadinstitute/seqr-loading-pipelines#249]
What are the differences between the reference data paths:

```text
gs://seqr-reference-data/GRCh37/all_reference_data/combined_reference_data_grch37.ht/
gs://seqr-reference-data/GRCh38/all_reference_data/combined_reference_data_grch38.ht/
```

and these?

```text
gs://seqr-reference-data/GRCh37/all_reference_data/v2/combined_reference_data_grch37-2.0.0.ht/
gs://seqr-reference-data/GRCh37/all_reference_data/v2/combined_reference_data_grch37-2.0.1.ht/
gs://seqr-reference-data/GRCh37/all_reference_data/v2/combined_reference_data_grch37-2.0.2.ht/
gs://seqr-reference-data/GRCh37/all_reference_data/v2/combined_reference_data_grch37-2.0.3.ht/

gs://seqr-reference-data/GRCh38/all_reference_data/v2/combined_reference_data_grch38-2.0.0.ht/
gs://seqr-reference-data/GRCh38/all_reference_data/v2/combined_reference_data_grch38-2.0.1.ht/
gs://seqr-reference-data/GRCh38/all_reference_data/v2/combined_reference_data_grch38-2.0.2.ht/
gs://seqr-reference-data/GRCh38/all_reference_data/v2/combined_reference_data_grch38-2.0.3.ht/
```

**Comment by mike-w-wilson** [comment]
Hi @tommyli,
The two files in the first block of code should be a copy of the the most recent version in the bottom block with the exception of `gs://seqr-reference-data/GRCh37/all_reference_data/v2/combined_reference_data_grch37-2.0.3.ht/` which does not exist. The hail library doesn't allow in-place overwrites so when we want to update a single annotation in the reference table, we update that annotation and then write the data out to a new version `gs://seqr-reference-data/...grch37-2.0.2.ht/` and then copy it to `gs://seqr-reference-data/...grch37.ht/`. This avoids having to rerun the massive joins to create the large ref table. We have since moved towards using the versions in our pipeline to better track changes.

**Comment by tommyli** [comment]
Thanks @mike-w-wilson.  Can I also assume that

```text
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.ht
```

is pointing to the latest of these?  I.e. `clinvar.GRCh38.2021-06-19.ht`, assuming it exists?

```text
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2020-03-29.ht/
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2020-06-02.ht/
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2020-06-15.ht/
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2020-08-03.ht/
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2020-09-05.ht/
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2020-12-26.ht/
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2021-03-28.ht/
gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2021-06-19.ht/
```

**Comment by tommyli** [comment]
Another question I had is whether there are details on where, when and versions of data sources that form these combined reference datasets?

**Comment by bpblanken** [comment]
Closing because related to doing things manually in v2.  v3 has consistent paths.
