### ISSUE TITLE
RSID not exporting

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr-loading-pipelines#340]
The rsid field is blank in elasticsearch. This seems to have been true since May 2021

**Comment by mike-w-wilson** [comment]
Looking into this, rsid is present in our variant MT gs://seqr-datasets/v02/GRCh38/RDG_WGS_Broad_Internal/v30/RDG_WGS_Broad_Internal.mt and there hasnt been a code change for the row annotation in 3 years. Will continue investigating.

**Comment by mike-w-wilson** [comment]
VCFs are delivered with rsids and we do not annotate that field again. I think their database is a bit dated for the annotation because there are variants in our callset that exist in gnomAD with rsids but the field is blank in our VCF e.g. 1-857462-G-A is missing an rsid in our VCF but in gnomad it is rs565193012. Hail also seems to treat the ID  field  as any other field on import...which makes sense...so when we split multi-allelics the rsid field is erroneously annotated...e.g. in our vcf we have the multi allelic
chr1	10144	rs144773400	TA	T,CA,*,GA
We read that, split it and the fields become
chr1:10144	["T","C"]	"rs144773400"	
chr1:10144	["T","G"]	"rs144773400"	
chr1:10144	["TA","T"]	"rs144773400"
even though rs144773400 is the rsid for 1-10144-TA-T . 1-10144-T-G does not have an rsid and 1-10144-T-C is rs1570391815 . gnomAD keeps a dbsnp ref dataset so  we can annotate post split if this is something Anne wants, can check in with her on priority.

**Comment by lynnpais** [comment]
Working in v3
