### ISSUE TITLE
pipeline-runner - exec format error

### ISSUE THREAD

**Issue by oferisak** [broadinstitute/seqr-loading-pipelines#363]
following up on issue #362 - when I try and create the pipeline runner using docker-compose and the instructions provided [here](https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md)
I get the following error message: 

$ docker-compose up pipeline-runner
Creating network "seqr_default" with the default driver
Pulling pipeline-runner (gcr.io/seqr-project/pipeline-runner:gcloud-prod)...
gcloud-prod: Pulling from seqr-project/pipeline-runner
08957e96ae93: Pull complete
...
914d8fd3ab7d: Pull complete
Digest: sha256:3aec7a0679cf73642c97d7d622ec36b414263dd6b08181b1e810d099a4e697bb
Status: Downloaded newer image for gcr.io/seqr-project/pipeline-runner:gcloud-prod
Creating elasticsearch ... done
Creating seqr_pipeline-runner_1 ... done
Attaching to seqr_pipeline-runner_1
**pipeline-runner_1  | exec /entrypoint.sh: exec format error
seqr_pipeline-runner_1 exited with code 1**

[exploring the issue,](https://stackoverflow.com/questions/73285601/docker-exec-usr-bin-sh-exec-format-error) I understand that the problem is that the pipeline-runner image is built in a different platform than my machine (linux/amd64)
uname -a output: x86_64 x86_64 x86_64 GNU/Linux

the only solution I found was to download and build the pipeline-runner docker locally using buildx and the correct platform.
is there a better solution that allows me to use only the docker-compose installation?

**Comment by hanars** [comment]
I am confused what you are asking here. In https://github.com/broadinstitute/seqr-loading-pipelines/issues/362 you say you are building the docker image yourself and I directed you to the commit you should use to build that. Then you say here that you are unable to run the prebuilt image on amd64, which you already knew which is why you are building it yourself

seqr is not supported for amd64, you are correct that the only way to get that working is to build it yourself. To use seqr in a well supported way, run it on debian

**Comment by oferisak** [comment]
Thank you for clarifying this. I just wanted to make sure that indeed, there is no way to run seqr on my amd64 without building it myself.
