### ISSUE TITLE
Add overlapping tag for SV data

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#458]
**Is your feature request related to a problem? Please describe.**
Need a way to know which variants were in previous rounds of SV data.

**Describe the solution you'd like**
Add overlapping tag to variants that overlap with the previous round(s) of SV data loaded to seqr. This is separate from the identical call which is for variants that are identical between rounds. 

**Describe alternatives you've considered**
NA

**Additional context**
Part of the SV v3 feedback discussed in #seqr-dev

**Comment by hanars** [comment]
Lynn said we want to show "overlapping" in this ticket. However, thats not something we can tell from data we have. What I was saying in slack is that we should not go for the behavior Lynn asked for in the ticket, we should go for whichever annotation is accurate.  `was_previously_called & concordant_genotype` is functionally equivalent to `prev_call`, not to `prev_overlap`. For gCNV we have some calls that are identical, some which are overlapping but with different coordinates, and some that are totally new. For WGS SVs all we have is whether it is identical to a previous call or not, and in the case of not we assume it is new. 

It is out of scope for us to go back and ask Alba to also indicate overlapping calls in the raw data, when we talked about that in meetings she indicated that thats nearly impossible with how the caller works. Looking into the original document Lynn delivered, her actual issue was that an identical call had no flag, so her issue will be solved by adding the identical tag and not the overlapping tag

**Comment by bpblanken** [comment]
👍 .  Just want to Make sure @lynnpais understands, since this ticket was written after that discussion.  Thanks for clarifying!
