### ISSUE TITLE
Turn on permit_shuffle in split_multi_hts

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr-loading-pipelines#523]
AnVIL loading requests often have keys out of order due to the VCFs containing a multiallelic and biallelic row entry for the same locus. This causes hail to throw an RVD key error. Using the `permit_shuffle` option in `split_multi_hts` fixes this issue but is costly for datasets that are already sorted so we do not want this switched on in all cases. Having this switched on for AnVIL requests only is the current desired behavior. Adding this would allow us to use a single version of the loading pipeline instead of flipping to a dev version that flips this switch on when necessary.

**Comment by bpblanken** [comment]
Looks like there's been some recent discussion about this issue: https://discuss.hail.is/t/when-running-split-multi-hts-i-received-a-key-out-of-order-error-why-do-i-receive-that-and-what-should-i-do/1978/5.

Can we maybe just do what was recommended there and split the bi-allelic from the multi-allelic rows?

**Comment by bpblanken** [comment]
Docs change was here: https://github.com/hail-is/hail/pull/10213/files

**Comment by mike-w-wilson** [comment]
I'm not sure what the right approach is. William looked into this last year and it looks like maybe doing a check for duplicate loci first, and then flipping that permit shuffle parameter depending on the check would also work? https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/permit_shuffle.20on.20hl.2Esplit_multi_hts/near/272966747 . I think the dataset split, split multis in only the multiallelic dataset, join with biallelic might shuffle anyways since those the keys would need to be put back in order after the split?

**Comment by bpblanken** [comment]
Do we have any idea what "expensive" means here in comparison to the rest of our pipeline?  For example, if the normal `split_multi_hts` takes 1 minute on average and with shuffle enabled it takes 3 minutes, that's quite bad, but is small potatoes in comparison to things like spinning up a dataproc cluster or elastic search export.  

Per [this comment](https://discuss.hail.is/t/when-running-split-multi-hts-i-received-a-key-out-of-order-error-why-do-i-receive-that-and-what-should-i-do/1978/2), the splitting should be efficient, though I don't understand why.  I also would be surprised if we weren't already shuffling elsewhere in the pipeline.

**Comment by bpblanken** [comment]
I did some more digging on this:

Here's a discussion: https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/Alternatives.20split_multi_hts.20with.20shuffle where I learned that we're doing a [shuffle](https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/Alternatives.20split_multi_hts.20with.20shuffle/near/226149132) already because we're not setting `left_aligned` is being passed as `false`.  The "split multis in only the multiallelic dataset, join with biallelic" approach is described as a sorted merge join that avoids a shuffle.  

Here'a another discussion: https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/HailException.3A.20RVD.20error where it seems like `shuffle` is fine with `use_new_shuffle=1`, which I think is a hail optimization to improve upon spark's shuffling capabilities.

**Comment by bpblanken** [comment]
I did some more digging on this:

Here's a discussion: https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/Alternatives.20split_multi_hts.20with.20shuffle where I learned that we're doing a [shuffle](https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/Alternatives.20split_multi_hts.20with.20shuffle/near/226149132) already because we're not setting `left_aligned` is being passed as `false`.  The "split multis in only the multiallelic dataset, join with biallelic" approach is described as a sorted merge join that avoids a shuffle.  

Here'a another discussion: https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/HailException.3A.20RVD.20error where it seems like `shuffle` is fine with `use_new_shuffle=1`, which I think is a hail optimization to improve upon spark's shuffling capabilities.
