### ISSUE TITLE
Include Submitter information from clinvar

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#677]
**Is your feature request related to a problem? Please describe.**
We'd like to track variants submitted to ClinVar by the Broad team.

**Describe the solution you'd like**
Be able to track submissions from our team [Broad Institute Rare Disease Group, Broad Institute](https://www.ncbi.nlm.nih.gov/clinvar/submitters/506627/).

Do this by always including submitter information in clinvar reference data

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by bpblanken** [comment]
I found the old ticket https://github.com/broadinstitute/seqr-loading-pipelines/issues/385

**Comment by lynnpais** [comment]
Duplicate

**Comment by larrybabb** [comment]
ClinVar produces a tab-delimited file every release called `submission_summary.txt.gz` in their ftp folder `https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/`.  It has the clinvar variation_id in col 1, the submitter name in col 10 and the submission id (SCV id) in col 11.  If you can join on the clinvar variation_id then you could find the unique submitter names per variant.  I think this is the path of least resistance. ClinVar has been reliably providing this file for years, I don't think they will stop without advanced notice since it was requested by the community some time ago.
