### ISSUE TITLE
VEPic

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr-loading-pipelines#686]

**Comment by bpblanken** [comment]
Plugins to add:
- MANE
- UTRAnnotator
- Alphamissense (requires 110)
- SliceRegion

VEP init script here: https://github.com/broadinstitute/gnomad_methods/blob/main/init_scripts/vep105-init.sh

Plan is:
- Bump to 110 on dataproc and get it working with custom config and init.
- Ensure bugs Qin fixed in VEP config are covered.
- Once it's working, reach out to hail team to attempt to get 110 into hail.

**Comment by bpblanken** [comment]
Details from Qin:

```
I'm sending you the corrected version of VEP 105 as attached, which should have been used in this script: https://github.com/broadinstitute/gnomad_methods/blob/main/init_scripts/vep105-init.sh

I was discussing this with Hail Team about some errors: 
https://hail.zulipchat.com/#narrow/stream/223457-Hail-Batch-support/topic/VEP.20json.20schema.20structure.20gets.20missing.20fields

Longer discussion with Wenhan and others can be found here: https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/VEP.20.22docker.20not.20found.22.20in.20Hail.200.2E2.2E109-b71b065e4bb6
```

**Comment by KoalaQin** [comment]
Actually, the correct one should be the attached one in the email: 
[vep105-init_mod.sh.txt](https://github.com/broadinstitute/seqr-loading-pipelines/files/14605122/vep105-init_mod.sh.txt)

**Comment by KoalaQin** [comment]
I also found in VEP repo people were asking how to get a json schema for Hail: https://github.com/Ensembl/ensembl-vep/issues/658.

**Comment by bpblanken** [comment]
complete!
